CREATE VIEW book AS
    SELECT book_branch.book_id, book_bbid.bbid, book_v.name, book_revision.book_tree_id, branch.rev_id FROM ((((((bookbrainz_v.branch JOIN bookbrainz_v.book_branch ON ((book_branch.branch_id = branch.branch_id))) JOIN bookbrainz_v.book_revision USING (rev_id)) JOIN bookbrainz_v.book USING (book_id)) JOIN bookbrainz_v.book_bbid USING (book_id)) JOIN bookbrainz_v.book_tree USING (book_tree_id)) JOIN bookbrainz_v.book_v USING (version)) WHERE (branch.master = true);

CREATE VIEW edition AS
    SELECT edition_branch.edition_id, edition_bbid.bbid, edition_v.name, edition_tree.book_id, edition_v.year, edition_tree.publisher_id, edition_v.country_iso_code, edition_v.language_iso_code, edition_v.isbn, edition_v.edition_index, edition_v.format, edition_revision.edition_tree_id, branch.rev_id FROM ((((((bookbrainz_v.branch JOIN bookbrainz_v.edition_branch USING (branch_id)) JOIN bookbrainz_v.edition_revision USING (rev_id)) JOIN bookbrainz_v.edition USING (edition_id)) JOIN bookbrainz_v.edition_bbid USING (edition_id)) JOIN bookbrainz_v.edition_tree USING (edition_tree_id)) JOIN bookbrainz_v.edition_v USING (version)) WHERE (branch.master = true);

CREATE VIEW person AS
    SELECT person_branch.person_id, person_bbid.bbid, person_v.name, person_revision.person_tree_id, branch.rev_id FROM ((((((bookbrainz_v.branch JOIN bookbrainz_v.person_branch ON ((person_branch.branch_id = branch.branch_id))) JOIN bookbrainz_v.person_revision USING (rev_id)) JOIN bookbrainz_v.person USING (person_id)) JOIN bookbrainz_v.person_bbid USING (person_id)) JOIN bookbrainz_v.person_tree USING (person_tree_id)) JOIN bookbrainz_v.person_v USING (version)) WHERE (branch.master = true);

CREATE VIEW publisher AS
    SELECT publisher_branch.publisher_id, publisher_bbid.bbid, publisher_v.name, publisher_revision.publisher_tree_id, branch.rev_id FROM ((((((bookbrainz_v.branch JOIN bookbrainz_v.publisher_branch ON ((publisher_branch.branch_id = branch.branch_id))) JOIN bookbrainz_v.publisher_revision USING (rev_id)) JOIN bookbrainz_v.publisher USING (publisher_id)) JOIN bookbrainz_v.publisher_bbid USING (publisher_id)) JOIN bookbrainz_v.publisher_tree USING (publisher_tree_id)) JOIN bookbrainz_v.publisher_v USING (version)) WHERE (branch.master = true);
